server:
  port: 8081

spring:
  application:
    name: db-load-app
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    platform: oracle
    username: TSTNWBRUMAST
    password: root
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

data:
  mySqlDataSource:
    url: jdbc:mysql://localhost/rsdev?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true
    platform: mysql
    username: root
    password: roots
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true